
CREATE TABLE Shippers (
    ShipperID INT NOT NULL GENERATED ALWAYS AS IDENTITY, 
    CompanyName STRING NOT NULL, 
    Phone STRING NULL
);

ALTER TABLE Shippers 
ADD CONSTRAINT PK_Shippers PRIMARY KEY (ShipperID);
